spring:
  application:
    name: micro-weather-web-server
  thymeleaf:
    cache: false
  cloud:
    config:
      profile: dev
      uri: http://localhost:8917/


server:
  port: 80
  servlet:
    context-path: /mww

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7790/eureka



