spring:
  application:
    name: micro-weather-configcenter-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xchb-null/micro-weather
          search-paths: config-repo

server:
  port: 8917

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7790/eureka



